/**
 * Runs once before the whole Playwright suite (wired via playwright.config.ts
 * `globalSetup`). Caps the long-lived local Supabase dev DB's volatile
 * transactional tables back to zero rows.
 *
 * None of these tables carry seed data — supabase/seed.sql and
 * scripts/seed-dev-data.ts never insert into tabs/orders/order_items/
 * payments/refunds/refund_items/bank_transfers — every row in them is
 * generated by a PRIOR e2e run's checkout/refund/payment flows and never
 * cleaned up. resetTestState() (e2e/helpers/supabase.ts) runs per-TEST and
 * deliberately does not delete this history (specs within one file often
 * assert against data an earlier test in the same file created); this is
 * the one-time, whole-suite equivalent that a long-lived shared local DB
 * still needs.
 *
 * Root cause this addresses: a long enough date range on a Reports-page
 * table backed by a raw (non-aggregated) query — e.g. RefundsRegister,
 * which fetches every `refunds` row in range with no server-side limit —
 * forces a large synchronous render once the underlying table has
 * accumulated thousands of historical rows, which can make the very next
 * Playwright click land mid-render and get intercepted by <html>. See
 * e2e/reports/report-tabs.spec.ts "Phase 24: retained new report tabs
 * render without crash".
 */
import { getServiceClient } from './helpers/supabase';

/** Deletion order respects FK constraints (verified against the local schema):
 *  payments.refund_id -> refunds and refunds.original_payment_id -> payments
 *  are mutually RESTRICT, so payments.refund_id must be nulled before either
 *  side can be deleted. bank_transfers/refund_items are RESTRICT children of
 *  payments/refunds+order_items respectively and must go first. Deleting
 *  `tabs` last cascades orders -> order_items automatically. */
async function pruneTransactionalHistory(): Promise<void> {
  const admin = getServiceClient();

  const { error: nullRefundIdError } = await admin
    .from('payments')
    .update({ refund_id: null })
    .not('refund_id', 'is', null);
  if (nullRefundIdError) throw new Error(`prune: unlink payments.refund_id failed: ${nullRefundIdError.message}`);

  for (const table of ['bank_transfers', 'refund_items', 'refunds', 'payments', 'tabs'] as const) {
    const { error } = await admin.from(table).delete().not('id', 'is', null);
    if (error) throw new Error(`prune: DELETE FROM ${table} failed: ${error.message}`);
  }
}

export default async function globalSetup(): Promise<void> {
  // Only ever prune the local dev Supabase instance every other e2e helper
  // targets — never the real remote project (see e2e/remote-smoke, which
  // uses a separate .env.remote-e2e and must never see this file run).
  const url = process.env['VITE_SUPABASE_URL'] ?? '';
  if (!/^https?:\/\/(127\.0\.0\.1|localhost)(:|\/)/.test(url)) return;

  await pruneTransactionalHistory();
}
